baseURL = "https://wlanwizard.github.io/interframe-blog/"
languageCode = 'en-us'
title = 'interframe.space - a wifi networking blog'

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[params]
  mainSections = ["posts"]   # helps themes know which section to list on home

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10