baseURL = "https://wlanwizard.github.io/interframe-blog/"
languageCode = 'en-us'
title = 'interframe.space - a wifi networking blog'

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"