baseURL = "https://blog.interframe.space/"
languageCode = "en-us"
title = "interframe.space - a wifi networking blog"

# Make sure Hugo uses your project's default folders
staticDir = ["static"]

[module]
  # Mount YOUR site dirs (these lines make your local static/ visible)
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "data"
    target = "data"

  # Theme import
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[params]
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

[markup.goldmark.renderer]
  unsafe = true